# Generated by Django 4.2.11 on 2026-05-11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bundle_type', models.CharField(choices=[('FREE', 'Experience Pass'), ('LITE', 'Lite Pass'), ('SOCIAL', 'Social Plus'), ('POWER', 'Power User'), ('STREAMER', 'Streamer'), ('ELITE', 'Elite Pass')], max_length=20)),
                ('description', models.TextField()),
                ('data_gb', models.CharField(max_length=50)),
                ('speed_mbps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_le', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bundles',
                'ordering': ['price_le'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('orange_pin', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_activation_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending PIN'), ('AUTHENTICATING', 'Awaiting SMS Link'), ('SYNCING', 'Synchronizing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bundles.bundle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bundles.bundle')),
                ('last_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bundles.order')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_response', models.JSONField(default=dict)),
                ('is_success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='bundles.order')),
            ],
        ),
    ]