# Generated by Django 6.0.5 on 2026-05-13 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='starlink_app.bundle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='otp_activation_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
